name: Continuous Integration

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix develop -c mill _.test
